parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: Detoditoonline
    database_user: detoditoonline
    database_password: detoditoonline
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 5c105ef464613208e610e1519c265efbc2
    database_path: null
