<?php

namespace Proxies\__CG__\Detoditoonline\ComprasBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Compra extends \Detoditoonline\ComprasBundle\Entity\Compra implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function Compra()
    {
        $this->__load();
        return parent::Compra();
    }

    public function getId_compra()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id_compra"];
        }
        $this->__load();
        return parent::getId_compra();
    }

    public function getId_producto()
    {
        $this->__load();
        return parent::getId_producto();
    }

    public function setId_producto($id_producto)
    {
        $this->__load();
        return parent::setId_producto($id_producto);
    }

    public function getId_carrito()
    {
        $this->__load();
        return parent::getId_carrito();
    }

    public function setId_carrito($id_carrito)
    {
        $this->__load();
        return parent::setId_carrito($id_carrito);
    }

    public function getCantidad()
    {
        $this->__load();
        return parent::getCantidad();
    }

    public function setCantidad($cantidad)
    {
        $this->__load();
        return parent::setCantidad($cantidad);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id_compra', 'cantidad', 'id_producto', 'id_carrito');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}