parameters:
#    domicilio.example.class: Detoditoonline\DomicilioBundle\Example

services:
#    domicilio.example:
#        class: %domicilio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
